spec/01_concepts.md
spec/02_state.md
spec/03_state_transitions.md
spec/04_messages.md
spec/05_begin_block.md
spec/06_end_block.md
spec/07_events.md
spec/08_params.md
spec/README.md

Add spec doc from [b-harvest/Liquidity-Module-For-the-Hub](https://github.com/b-harvest/Liquidity-Module-For-the-Hub)

Add spec documentation

---

app/app.go
app/encoding.go
x/liquidity/client/cli/query.go
x/liquidity/client/cli/tx.go
x/liquidity/keeper/batch.go
x/liquidity/keeper/grpc_query.go
x/liquidity/keeper/liquidity_pool.go
x/liquidity/keeper/swap.go
x/liquidity/keeper/swap_test.go
x/liquidity/types/params.go
x/liquidity/types/swap.go
x/liquidity/types/swap_test.go

ref
- https://github.com/tendermint/liquidity/issues/29

Fix bugs on swap execution logic

---

x/liquidity/keeper/liquidity_pool.go
x/liquidity/keeper/swap.go
x/liquidity/types/swap.go

- fix to collect a SwapFee from ExchangedCoin  from OfferCoin
- but It should be half, half fee logic, WIP

Add validity logic, Fix fee bug

---

x/liquidity/spec/05_begin_block.md
x/liquidity/spec/06_end_block.md

add spec of begin-block and update end-block according to added statuses of PoolBatchMsg from https://github.com/tendermint/liquidity/pull/62

update spec of begin, end-block

---

config.yml

`config.yml` file is needed for [Starport](https://github.com/tendermint/starport). With this change, users will be able to run `starport serve` to launch blockchain in development.
Similar PR for `gaia`: https://github.com/cosmos/gaia/pull/535

Added config.yml for Starport

---

app/test_helpers.go
x/liquidity/keeper/liquidity_pool.go
x/liquidity/keeper/swap.go
x/liquidity/keeper/swap_test.go
x/liquidity/types/errors.go
x/liquidity/types/msgs.go
x/liquidity/types/params.go
x/liquidity/types/swap.go

-  FractionalMatchRato logic bug
-  Skip offsetting exchanged coin fee to multisend, It cause temporary insufficient funds when InputOutputCoins
-  To using RemainingOfferCoin
-  Increase test randomness

Fix Swap bugs

---

go.mod
go.sum

https://github.com/cosmos/cosmos-sdk/compare/v0.41.0...v0.41.3

rebase cosmos-sdk to 0.41.3

---

app/app.go
app/doc.go
app/encoding.go
app/export.go
app/genesis.go
app/sim_test.go
app/test_helpers.go
x/liquidity/module.go

revert DONTCOVER for module.go and app/ for module coverage

---

README.md
go.mod
go.sum

https://github.com/cosmos/cosmos-sdk/compare/v0.41.4...v0.42.0
closes: #XXXX
---

update sdk to 0.42.0

---

x/liquidity/keeper/grpc_query.go
x/liquidity/keeper/grpc_query_test.go
x/liquidity/keeper/keeper_test.go

This PR cleans up the overall codes in `grpc_query.go` in keeper package.
---

Clean up GRPC query methods

---

x/liquidity/types/params.go

Fix lack of the parameter on format string

---

README.md
app/app.go
go.mod
go.sum

https://github.com/cosmos/gaia/compare/v4.0.6...v4.1.0
closes: #XXXX
---

Update sdk to 0.42.1 for fix vulnerability

---

x/liquidity/keeper/liquidity_pool.go
x/liquidity/keeper/swap.go
x/liquidity/types/swap.go

To minimize decimal errors during calculation, use sdk.Dec and truncate it to sdk.Int only at the end.
See #125 
---

Convert sdk.Int to sdk.Dec where applicable

---

.github/workflows/test.yml

This PR adds test-simulation in code coverage
---

Add test-simulation in codecov github action

---

x/liquidity/types/swap.go

Fix swap bug that ignores last order in orderbook.
---

Fix swap bug

---

go.mod
go.sum

update sdk version to 0.42.2

---

x/liquidity/keeper/liquidity_pool.go
x/liquidity/keeper/swap_test.go
x/liquidity/types/genesis_test.go
x/liquidity/types/liquidity_pool.go

Add logics for refund remaining offerCoinFee

---

go.mod
go.sum

update sdk version to v0.42.3

---

x/liquidity/handler_test.go
x/liquidity/keeper/batch.go
x/liquidity/keeper/liquidity_pool.go
x/liquidity/keeper/liquidity_pool_test.go
x/liquidity/keeper/msg_server_test.go
x/liquidity/types/errors.go

Add logics for depleted pool, withdrawing all cases 

---

.gitattributes

Add generated js/ts code patterns to linguist-generated

---

x/liquidity/keeper/invariants.go
x/liquidity/keeper/liquidity_pool.go
x/liquidity/keeper/liquidity_pool_test.go

Fix ratio comparison logic in invariant checks

---

.build.sh
Makefile

Add build-reproducible command

---

x/liquidity/keeper/common_test.go
x/liquidity/keeper/invariants.go
x/liquidity/keeper/invariants_test.go
x/liquidity/keeper/liquidity_pool.go
x/liquidity/keeper/liquidity_pool_test.go

Fix withdraw issues

---

x/liquidity/keeper/invariants.go
x/liquidity/keeper/liquidity_pool.go

Fix invariant check issue

---

doc/client.md
x/liquidity/client/cli/query.go
x/liquidity/client/cli/tx.go
x/liquidity/keeper/liquidity_pool.go

Fix appName on example, empty event

---

README.md
doc/client.md
x/liquidity/client/cli/query.go
x/liquidity/client/cli/tx.go

It is PR to get the Liquidityd Client CLI Documentation QA suggestions based on the sources, continues to after https://github.com/tendermint/liquidity/pull/212
For suggestions, do not make changes to the `client.md` file. Instead, make changes edits to the description of CLI directly in go file
- `x/liquidity/client/cli/query.go`
- `x/liquidity/client/cli/tx.go`
Then I'll fix and apply suggestions to the `client.md` file before merging.
linked issue: https://github.com/tendermint/liquidity/issues/177

Liquidityd Client CLI Documentation QA

---

Makefile
x/liquidity/client/cli/query.go
x/liquidity/client/cli/tx.go

Querying twice in some CLI command

---

x/liquidity/keeper/liquidity_pool.go

This prevents code to panic when a fresh account tries to create a pool
closes: #370
---

Do not call GetAccount for address in the MsgCreatePool

---

x/liquidity/keeper/liquidity_pool.go
x/liquidity/keeper/liquidity_pool_test.go
x/liquidity/keeper/store.go
x/liquidity/keeper/swap.go
x/liquidity/module.go
x/liquidity/spec/02_state.md
x/liquidity/types/params.go

Optimize storing pool by reserveAcc, remove redundant codes

---

app/app.go

Add UpgradeHandler to add liquidity module on gaia

---

x/liquidity/keeper/batch.go
x/liquidity/keeper/batch_test.go
x/liquidity/keeper/liquidity_pool.go
x/liquidity/keeper/msg_server.go
x/liquidity/types/swap.go

Calculate order expiry span height correctly

---

x/liquidity/client/cli/cli_test.go
x/liquidity/keeper/batch.go
x/liquidity/keeper/liquidity_pool.go
x/liquidity/types/events.go
x/liquidity/types/genesis.go
x/liquidity/types/keys.go
x/liquidity/types/msgs.go
x/liquidity/types/msgs_test.go
x/liquidity/types/utils.go

Fix documentation of the code

---

x/liquidity/keeper/invariants.go
x/liquidity/keeper/invariants_test.go
x/liquidity/keeper/liquidity_pool.go

Decrease error rate threshold and merge invariant checks

---

x/liquidity/keeper/batch_test.go
x/liquidity/keeper/invariants_test.go

Improve tests

---

x/liquidity/keeper/liquidity_pool.go

Fix module specific logger

---

cmd/liquidityd/cmd/genaccounts.go

Fix add genesis account cli command

---

x/liquidity/keeper/liquidity_pool.go

use IsDepletedPool()

---

app/test_helpers.go
x/liquidity/abci.go
x/liquidity/handler_test.go
x/liquidity/keeper/batch.go
x/liquidity/keeper/batch_test.go
x/liquidity/keeper/liquidity_pool.go
x/liquidity/keeper/liquidity_pool_test.go
x/liquidity/keeper/msg_server.go
x/liquidity/keeper/msg_server_test.go
x/liquidity/keeper/store_test.go
x/liquidity/keeper/swap_test.go
x/liquidity/types/swap_test.go

To keep consistency between message names and method names, change outdated method names.
---

Use correct method names

---

x/liquidity/keeper/invariants.go

this might not have significant effect, but is for safety
closes: #393 
---

Prevent divide-by-zero panic

---

x/liquidity/keeper/batch.go
x/liquidity/keeper/liquidity_pool.go

Handle errors during batch execution correctly

---

Makefile
cmd/liquidityd/main.go
x/liquidity/simulation/operations.go
x/liquidity/types/events.go

Exclude the files generated by statik and apply nolint rules correctly.
---

Fix lint command

---

x/liquidity/keeper/batch.go
x/liquidity/keeper/batch_test.go
x/liquidity/keeper/liquidity_pool.go

this reverts changes made in 5052628c4b27266f979fcf845288c080b791489e
and also fix test
closes: #XXXX
---

Log errors, not panic in batch execution

---

x/liquidity/handler_test.go
x/liquidity/keeper/batch_test.go
x/liquidity/keeper/genesis_test.go
x/liquidity/keeper/liquidity_pool_test.go
x/liquidity/keeper/msg_server_test.go
x/liquidity/keeper/querier_test.go
x/liquidity/keeper/swap_test.go
x/liquidity/types/genesis_test.go
x/liquidity/types/params_test.go
x/liquidity/types/swap_test.go

Add exact equal checking to error cases of test codes

---

x/liquidity/spec/08_params.md
x/liquidity/types/params.go
x/liquidity/types/params_test.go

This PR for adjusting default parameters of liquidity module
- Fix name of `PoolType` 1 and add description
- Fix `PoolCreationFee` to 40,000,000
- Fix `WithdrawFeeRate` to Decimal zero
---

Adjust default params

---

.golangci.yml
go.mod
go.sum

Bump cosmos-sdk version to [v0.42.6](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.42.6) for gaia deps https://github.com/cosmos/gaia/pull/889
closes: #XXXX
---

Bump cosmos-sdk version v0.42.5 to v0.42.6

---

doc/Gravity_DEX_V2.0_LitePaper.md

this is not ready for merge yet, just for review.

V2.0 Lite Paper

---

x/liquidity/client/cli/cli_test.go
x/liquidity/client/testutil/cli_helpers.go
x/liquidity/keeper/msg_server.go
x/liquidity/spec/04_messages.md
x/liquidity/spec/08_params.md

fix: exclude circuit breaking logic for MsgWithdrawWithinBatch

---

x/liquidity/client/cli/cli_test.go

fix: reduce gov time to test more deterministic

---

CHANGELOG.md
app/params/amino.go
app/params/proto.go
go.mod
go.sum
x/liquidity/client/cli/cli_test.go

build: bump cosmos-sdk to v0.44.5
